language: java
addons:
  sonarcloud:
    organization: "rasmussaks-github"

script:
  - ./gradlew test
  - sonar-scanner

services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres